# Generated by Django 5.1.6 on 2025-02-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Место')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Место')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('img', models.URLField(default='', verbose_name='Фото')),
                ('num', models.CharField(default='054-9140720', max_length=200, verbose_name='Номер телефона')),
                ('numlink', models.CharField(default='+549140720', max_length=200, verbose_name='Линк на номер')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.locations', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Девушка',
                'verbose_name_plural': 'Девушки',
            },
        ),
    ]
