# Generated by Django 5.1.6 on 2025-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_girls_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='girls',
            name='img10',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото10'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img2',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img3',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото3'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img4',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото4'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img5',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото5'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img6',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото6'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img7',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото7'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img8',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото8'),
        ),
        migrations.AddField(
            model_name='girls',
            name='img9',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Фото9'),
        ),
    ]
