# Generated by Django 5.1.6 on 2025-02-11 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText1', ckeditor.fields.RichTextField(default='none', verbose_name='Текст на верху сайта на главном странице')),
                ('mainText2', ckeditor.fields.RichTextField(default='none', verbose_name='Текст в конце сайта на главном странице')),
                ('logo', models.URLField(default='', verbose_name='Логотип')),
                ('logotxt', models.CharField(default='', max_length=200, verbose_name='Текст в логотипе')),
                ('footer', models.TextField(default='', verbose_name='Текст в подвале')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
