# Generated by Django 5.1.6 on 2025-02-11 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='footer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст в подвале'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='logotxt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Текст в логотипе'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='mainText1',
            field=ckeditor.fields.RichTextField(blank=True, default='none', null=True, verbose_name='Текст на верху сайта на главном странице'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='mainText2',
            field=ckeditor.fields.RichTextField(blank=True, default='none', null=True, verbose_name='Текст в конце сайта на главном странице'),
        ),
    ]
