# Generated by Django 5.1.6 on 2025-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainsettings_footer_alter_mainsettings_logotxt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='logo',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Логотип'),
        ),
    ]
